### PR TITLE
HNS-Client.xml-added argument to load external config file , pom.xml:…

### PR DESCRIPTION
**Pull request by AnumehaSrivastava05**
… added option to exclude proerties file from jar

### CODE REVIEW

**Comment by AnumehaSrivastava05** [comment]
Updated confluence document for external propertie
https://proactionca.ent.cgi.com/confluence/display/BCMOHAD/HNS-Install+HNClient+as+window+service

**Review by weskubo-cgi — CHANGES_REQUESTED** [review]
Changes look good but as mentioned (and confirmed by Patrick) we should include log4j2.properties as well.

**Comment by AnumehaSrivastava05** [comment]
Please review the changes for log4j .

**Review by weskubo-cgi — APPROVED** [review]
Changes look good.

**Pull request merged**
